"""SignTurk text-processing pipeline: word buffer → grammar → TTS.

Isolated from the LSTM model, FastAPI routes, UI, and 3D-avatar layers.
"""

from .buffer import BufferConfig, WordBuffer
from .grammar import (
    DECISION_LOG,
    DEFAULT_API_MODEL_KEY,
    DEFAULT_LOCAL_MODEL_KEY,
    DEFAULT_MODEL_KEY,
    MODEL_REGISTRY,
    PROMPT_TEMPLATES,
    PROMPT_VERSION,
    DecisionRecord,
    GrammarConfig,
    GrammarCorrector,
    GrammarResult,
    MLGrammarCorrector,
    ModelSpec,
    PromptSpec,
    RuleBasedCorrector,
    ValidationResult,
    apply_ablative,
    apply_accusative,
    apply_consonant_assimilation,
    apply_consonant_softening,
    apply_dative,
    apply_dative_suffix,
    apply_locative,
    apply_vowel_harmony,
    apply_vowel_narrowing,
    build_causal_prompt,
    build_seq2seq_prompt,
    build_zero_shot_messages,
    build_zero_shot_prompt,
    conjugate_present_continuous,
    list_available_models,
    list_prompt_versions,
    normalize_words,
    validate_ml_output,
)
from .pipeline import PipelineConfig, PipelineResult, SignTextPipeline
from .tts import TTSConfig, TTSSynthesizer, play_audio

__all__ = [
    "BufferConfig",
    "WordBuffer",
    "DECISION_LOG",
    "DEFAULT_API_MODEL_KEY",
    "DEFAULT_LOCAL_MODEL_KEY",
    "DEFAULT_MODEL_KEY",
    "MODEL_REGISTRY",
    "PROMPT_TEMPLATES",
    "PROMPT_VERSION",
    "DecisionRecord",
    "PromptSpec",
    "list_prompt_versions",
    "GrammarConfig",
    "GrammarCorrector",
    "GrammarResult",
    "MLGrammarCorrector",
    "ModelSpec",
    "RuleBasedCorrector",
    "ValidationResult",
    "apply_ablative",
    "apply_accusative",
    "apply_consonant_assimilation",
    "apply_consonant_softening",
    "apply_dative",
    "apply_dative_suffix",
    "apply_locative",
    "apply_vowel_harmony",
    "apply_vowel_narrowing",
    "build_causal_prompt",
    "build_seq2seq_prompt",
    "build_zero_shot_messages",
    "build_zero_shot_prompt",
    "conjugate_present_continuous",
    "list_available_models",
    "normalize_words",
    "validate_ml_output",
    "PipelineConfig",
    "PipelineResult",
    "SignTextPipeline",
    "TTSConfig",
    "TTSSynthesizer",
    "play_audio",
]
